spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hoangvuongquocanh76@gmail.com
spring.mail.password=cwbgqntxuloetydr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:mysql://mysql:3306/mail_record?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=180703
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8081